### ISSUE TITLE
Mount ssh auth sock to docker containers in MacOS

### ISSUE THREAD

**Issue by chenj100** [chenj100/archive#4]
Sometimes we want to `git clone` or `go get` inside containers, which requires accessing ssh auth sock on the host machine to be authenticated to the git repository when the repository only allows ssh access.

Somehow we need to use this magic path `/run/host-services/ssh-auth.sock` instead of the `SSH_AUTH_SOCK` env variable in MacOS.

https://docs.docker.com/desktop/mac/networking/#ssh-agent-forwarding

```yaml
services:
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
```
